# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rate
  pod 'Alamofire', '~>4.0'
  pod 'Kanna', '~> 4.0.0'
end
